/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.ufjf.dcc025.trabalho2.View.UserInterface.ManagementPanels;
import javax.swing.table.DefaultTableModel;
public class PatientListPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientListPanel
     */
    public PatientListPanel() {
        initComponents();
        modelo = new DefaultTableModel();  
        modelo.addColumn("Nome");  
        modelo.addColumn("Documento");  
        modelo.addColumn("Telefone");  
        modelo.addColumn("E-mail");
        patientTable.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rPatientPanel = new javax.swing.JPanel();
        patientList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        newPatientBtn1 = new javax.swing.JButton();
        registerPacientFrame = new javax.swing.JInternalFrame();
        pNameLabel = new javax.swing.JLabel();
        pMailLabel = new javax.swing.JLabel();
        pPhoneLabel = new javax.swing.JLabel();
        pDocLabel = new javax.swing.JLabel();
        completeBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        pNameField = new javax.swing.JTextField();
        pDocumentField = new javax.swing.JTextField();
        pPhoneField = new javax.swing.JTextField();
        pMailField = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(497, 715));

        patientTable.setAutoCreateRowSorter(true);
        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Documento", "Telefone", "E-mail"
            }
        ));
        patientTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(patientTable);

        javax.swing.GroupLayout patientListLayout = new javax.swing.GroupLayout(patientList);
        patientList.setLayout(patientListLayout);
        patientListLayout.setHorizontalGroup(
            patientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
                .addContainerGap())
        );
        patientListLayout.setVerticalGroup(
            patientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientListLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        newPatientBtn1.setText("Novo Paciente");
        newPatientBtn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newPatientBtn1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newPatientBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPatientBtn1ActionPerformed(evt);
            }
        });

        registerPacientFrame.setVisible(true);

        pNameLabel.setText("Nome: ");

        pMailLabel.setText("E-Mail:");
        pMailLabel.setToolTipText("");

        pPhoneLabel.setText("Telefone:");

        pDocLabel.setText("Documento:");

        completeBtn.setText("Concluído");
        completeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancelar");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerPacientFrameLayout = new javax.swing.GroupLayout(registerPacientFrame.getContentPane());
        registerPacientFrame.getContentPane().setLayout(registerPacientFrameLayout);
        registerPacientFrameLayout.setHorizontalGroup(
            registerPacientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPacientFrameLayout.createSequentialGroup()
                .addGroup(registerPacientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPacientFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(registerPacientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pDocLabel)
                            .addComponent(pNameLabel)
                            .addComponent(pPhoneLabel)
                            .addComponent(pMailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerPacientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pPhoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                            .addComponent(pDocumentField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pNameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pMailField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPacientFrameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(completeBtn)
                .addGap(48, 48, 48))
        );
        registerPacientFrameLayout.setVerticalGroup(
            registerPacientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPacientFrameLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(registerPacientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pNameLabel)
                    .addComponent(pNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(registerPacientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pDocLabel)
                    .addComponent(pDocumentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerPacientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pPhoneLabel)
                    .addComponent(pPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(registerPacientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pMailLabel)
                    .addComponent(pMailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(registerPacientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completeBtn)
                    .addComponent(cancelBtn))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout rPatientPanelLayout = new javax.swing.GroupLayout(rPatientPanel);
        rPatientPanel.setLayout(rPatientPanelLayout);
        rPatientPanelLayout.setHorizontalGroup(
            rPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rPatientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rPatientPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(newPatientBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rPatientPanelLayout.createSequentialGroup()
                        .addComponent(patientList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rPatientPanelLayout.createSequentialGroup()
                        .addComponent(registerPacientFrame)
                        .addContainerGap())))
        );
        rPatientPanelLayout.setVerticalGroup(
            rPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rPatientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPatientBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerPacientFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        registerPacientFrame.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rPatientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rPatientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limpaCampo(javax.swing.JTextField c){
        c.setText("");
    }
    
    private void completeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeBtnActionPerformed
        // TODO add your handling code here:
        Object[] data = {pNameField.getText(), pDocumentField.getText(), pPhoneField.getText(), pMailField.getText()};
        addRowsTo(modelo, data);
        limpaCampo(pNameField);
        limpaCampo(pDocumentField);
        limpaCampo(pMailField);
        limpaCampo(pPhoneField);
        this.registerPacientFrame.setVisible(false);
        
    }//GEN-LAST:event_completeBtnActionPerformed

    private void addRowsTo(DefaultTableModel table, Object[] args){
        table.addRow(args);
    }
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.registerPacientFrame.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void newPatientBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPatientBtn1ActionPerformed
        // TODO add your handling code here:
        this.registerPacientFrame.setVisible(true);
    }//GEN-LAST:event_newPatientBtn1ActionPerformed

    private DefaultTableModel modelo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton completeBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newPatientBtn1;
    private javax.swing.JLabel pDocLabel;
    private javax.swing.JTextField pDocumentField;
    private javax.swing.JTextField pMailField;
    private javax.swing.JLabel pMailLabel;
    private javax.swing.JTextField pNameField;
    private javax.swing.JLabel pNameLabel;
    private javax.swing.JTextField pPhoneField;
    private javax.swing.JLabel pPhoneLabel;
    private javax.swing.JPanel patientList;
    private javax.swing.JTable patientTable;
    private javax.swing.JPanel rPatientPanel;
    private javax.swing.JInternalFrame registerPacientFrame;
    // End of variables declaration//GEN-END:variables
}
