/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.ufjf.dcc025.trabalho2.view.UserInterface;
import br.ufjf.dcc025.trabalho2.view.UserInterface.ManagementPanels.RegisterFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class SecretaryPanel extends JPanel {

    /**
     * Creates new form SecretaryPanel
     * @param main
     */
    public SecretaryPanel(MainFrame main) {
        initComponents();
        mainPage = main;
        modelo = new DefaultTableModel();  
        modelo.addColumn("Nome");  
        modelo.addColumn("Documento");  
        modelo.addColumn("Telefone");  
        modelo.addColumn("E-mail");
        modelo.addColumn("Ocupação");
        patientTable.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SecretaryTabbedPane = new javax.swing.JTabbedPane();
        AppointsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AppointTable = new javax.swing.JTable();
        cancelAptBtn = new javax.swing.JButton();
        newAptBtn = new javax.swing.JButton();
        editAppointBtn = new javax.swing.JButton();
        UsersPane = new javax.swing.JPanel();
        patientList = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        newUserBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(1100, 500));

        AppointTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Paciente", "Médico", "Data", "Horário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AppointTable);

        cancelAptBtn.setText("Remover");
        cancelAptBtn.addActionListener(this::cancelAptBtnActionPerformed);

        newAptBtn.setText("Novo");

        editAppointBtn.setText("Editar");

        javax.swing.GroupLayout AppointsPanelLayout = new javax.swing.GroupLayout(AppointsPanel);
        AppointsPanel.setLayout(AppointsPanelLayout);
        AppointsPanelLayout.setHorizontalGroup(
            AppointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointsPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AppointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newAptBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editAppointBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelAptBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        AppointsPanelLayout.setVerticalGroup(
            AppointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointsPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(AppointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AppointsPanelLayout.createSequentialGroup()
                        .addComponent(newAptBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editAppointBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelAptBtn)))
                .addContainerGap(322, Short.MAX_VALUE))
        );

        SecretaryTabbedPane.addTab("Consultas", AppointsPanel);
        AppointsPanel.setVisible(false);

        patientTable.setAutoCreateRowSorter(true);
        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Documento", "Telefone", "E-mail", "Ocupação"
            }
        ));
        patientTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(patientTable);

        javax.swing.GroupLayout patientListLayout = new javax.swing.GroupLayout(patientList);
        patientList.setLayout(patientListLayout);
        patientListLayout.setHorizontalGroup(
            patientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
                .addContainerGap())
        );
        patientListLayout.setVerticalGroup(
            patientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientListLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        newUserBtn.setText("Novo Usuário");
        newUserBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newUserBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newUserBtn.addActionListener(this::newUserBtnActionPerformed);

        javax.swing.GroupLayout UsersPaneLayout = new javax.swing.GroupLayout(UsersPane);
        UsersPane.setLayout(UsersPaneLayout);
        UsersPaneLayout.setHorizontalGroup(
            UsersPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsersPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(UsersPaneLayout.createSequentialGroup()
                .addComponent(patientList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        UsersPaneLayout.setVerticalGroup(
            UsersPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(newUserBtn)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        SecretaryTabbedPane.addTab("Usuários", UsersPane);

        LogOutBtn.setText("LogOut");
        LogOutBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LogOutBtn.addActionListener(this::LogOutBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LogOutBtn))
                    .addComponent(SecretaryTabbedPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SecretaryTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        SecretaryTabbedPane.getAccessibleContext().setAccessibleName("tab");
        LogOutBtn.getAccessibleContext().setAccessibleName("LogOutBttn");
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        // TODO add your handling code here:
        this.mainPage.changeScreen("login");
    }//GEN-LAST:event_LogOutBtnActionPerformed
    
    private void cancelAptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAptBtnActionPerformed
        // TODO add your handling code here:
        this.AppointsPanel.setVisible(false);
    }//GEN-LAST:event_cancelAptBtnActionPerformed

    private void newUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserBtnActionPerformed
        // TODO add your handling code here:
        cadastro = new RegisterFrame();
    }//GEN-LAST:event_newUserBtnActionPerformed
    
    private final MainFrame mainPage;
    private final DefaultTableModel modelo;
    private RegisterFrame cadastro;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AppointTable;
    private javax.swing.JPanel AppointsPanel;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JTabbedPane SecretaryTabbedPane;
    private javax.swing.JPanel UsersPane;
    private javax.swing.JButton cancelAptBtn;
    private javax.swing.JButton editAppointBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton newAptBtn;
    private javax.swing.JButton newUserBtn;
    private javax.swing.JPanel patientList;
    private javax.swing.JTable patientTable;
    // End of variables declaration//GEN-END:variables
}
