/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.ufjf.dcc025.trabalho2.view.UserInterface;
import java.awt.CardLayout;

import javax.swing.JFrame;
import javax.swing.JPanel;

import br.ufjf.dcc025.trabalho2.view.UserInterface.ManagementPanels.PatientListPanel;
import br.ufjf.dcc025.trabalho2.view.UserInterface.ManagementPanels.SecondFrame;



public class SecretaryPanel extends JPanel {

    /**
     * Creates new form SecretaryPanel
     * @param main
     */
    public SecretaryPanel(MainFrame main) {
        initComponents();
        mainPage = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        consultPatients = new javax.swing.JButton();
        activeMedic = new javax.swing.JButton();
        AppointBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        AppointsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AppointTable = new javax.swing.JTable();
        cancelAptBtn = new javax.swing.JButton();
        newAptBtn = new javax.swing.JButton();
        editAppointBtn = new javax.swing.JButton();
        MedicList = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MedicTable = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(1190, 780));

        jToolBar1.setRollover(true);

        jLabel1.setText("Boas vindas, secretaria!");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jToolBar1.add(jLabel1);

        consultPatients.setText("Pacientes");
        consultPatients.setFocusable(false);
        consultPatients.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        consultPatients.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        consultPatients.addActionListener(this::consultPatientsActionPerformed);
        jToolBar1.add(consultPatients);

        activeMedic.setText("Médicos");
        activeMedic.setFocusable(false);
        activeMedic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        activeMedic.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        activeMedic.addActionListener(this::activeMedicActionPerformed);
        jToolBar1.add(activeMedic);

        AppointBtn.setText("Agendamentos");
        AppointBtn.setFocusable(false);
        AppointBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AppointBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AppointBtn.addActionListener(this::AppointBtnActionPerformed);
        jToolBar1.add(AppointBtn);

        LogOutBtn.setText("LogOut");
        LogOutBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LogOutBtn.addActionListener(this::LogOutBtnActionPerformed);
        jToolBar1.add(LogOutBtn);
        LogOutBtn.getAccessibleContext().setAccessibleName("LogOutBttn");

        AppointTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Paciente", "Médico", "Data", "Horário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AppointTable);

        cancelAptBtn.setText("Cancelar");
        cancelAptBtn.addActionListener(this::cancelAptBtnActionPerformed);

        newAptBtn.setText("Novo");

        editAppointBtn.setText("Editar");

        javax.swing.GroupLayout AppointsPanelLayout = new javax.swing.GroupLayout(AppointsPanel);
        AppointsPanel.setLayout(AppointsPanelLayout);
        AppointsPanelLayout.setHorizontalGroup(
            AppointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppointsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(editAppointBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newAptBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelAptBtn)
                .addGap(29, 29, 29))
            .addGroup(AppointsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        AppointsPanelLayout.setVerticalGroup(
            AppointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointsPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AppointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newAptBtn)
                    .addComponent(cancelAptBtn)
                    .addComponent(editAppointBtn))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        MedicTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Médico", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(MedicTable);

        javax.swing.GroupLayout MedicListLayout = new javax.swing.GroupLayout(MedicList);
        MedicList.setLayout(MedicListLayout);
        MedicListLayout.setHorizontalGroup(
            MedicListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
                .addContainerGap())
        );
        MedicListLayout.setVerticalGroup(
            MedicListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicListLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MedicList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AppointsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AppointsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MedicList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AppointsPanel.setVisible(false);
        MedicList.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        // TODO add your handling code here:
        this.mainPage.changeScreen("login");
    }//GEN-LAST:event_LogOutBtnActionPerformed
    
    private void consultPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultPatientsActionPerformed
        // TODO add your handling code here:
        SecondFrame novaJanela = new SecondFrame(new PatientListPanel());
        novaJanela.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        novaJanela.setVisible(true);
    }//GEN-LAST:event_consultPatientsActionPerformed

    private void AppointBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointBtnActionPerformed
        // TODO add your handling code here:
        this.AppointsPanel.setVisible(true);
    }//GEN-LAST:event_AppointBtnActionPerformed

    private void cancelAptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAptBtnActionPerformed
        // TODO add your handling code here:
        this.AppointsPanel.setVisible(false);
    }//GEN-LAST:event_cancelAptBtnActionPerformed

    private void activeMedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeMedicActionPerformed
        // TODO add your handling code here:
        if(this.MedicList.isVisible())
            this.MedicList.setVisible(false);
        else
            this.MedicList.setVisible(true);
    }//GEN-LAST:event_activeMedicActionPerformed
    
    private MainFrame mainPage;
    private CardLayout cardLayout;
    private javax.swing.JPanel jPanel2;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AppointBtn;
    private javax.swing.JTable AppointTable;
    private javax.swing.JPanel AppointsPanel;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JPanel MedicList;
    private javax.swing.JTable MedicTable;
    private javax.swing.JButton activeMedic;
    private javax.swing.JButton cancelAptBtn;
    private javax.swing.JButton consultPatients;
    private javax.swing.JButton editAppointBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton newAptBtn;
    // End of variables declaration//GEN-END:variables
}
